# Generated by Django 4.0.5 on 2022-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
