# Generated by Django 4.0.5 on 2022-06-07 11:37

import amazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to=amazon.models.user_directory_path),
        ),
    ]
